language: python
python:
  - "3.9.10"

addons:
  sonarcloud:
    organization: "isaacvega5" 
    token:
      secure: "JKrI2C1mHpNs4y6z3j5iOsw3W2VV9lb06khrArIZN60S7DoAObRKAdjL1NrsDHmgzwKbhlNJpM9E+tJ/RuthBI5ejgNv48XXtAsZdQzfI93FV3svu5FwW36ae50I0kMEU4gIoyUzZcRm5m5ykMWzX861SeKtkI7X6fUByBoNk4exmIIsEpJTBreySDYnEODMh8wCRJe5lAVCQkVX2nrR8BQHdBQ+Tx4Drv5Z7sSzgIFRwqecZJFFM5Ks4FjXhCjjOAfEbUjUaAkT6XRmepAxHBXuFXSl57HL3sNYB36dxbGar6iI2kEhBklf2WvNm0Ngjn66tZWMzhVbzJYVPKxn7BA70/9NS8VbTHe6LzB9+E/lh9t06bJOCs0gNdVqps+JgQ7XqYD7g4EIjJ1Bv4mZEEjtmNvQRLrayR9vYSwWu4nV/s2IC1CtvlF69Hgad0JMiayuF63eVJy2a/kSHMBBao6ZPe77tiQGO83v5cPFdeU5LCfFE/ZFf453+tOoWMYQ8ONo+z03iPJuNfKlf57iBe1J0GoSX4NKhny7bGqmmX6MWi216ujy8b9xe7QvOKOl11TPU/XjxPP8jxE56GfucsSOc+adQT2Ac67hAQkgcoGQYb/XZuzuYYW4apUQLocNeSvn25VhFuflQkMa+YQovgcG4Jx3KAtC7QuQdQDPlYM="
      
script:
  - python -m unittest discover -s tests
  - sonar-scanner