language: python
python:
  - "3.9.10"

addons:
  sonarcloud:
    organization: "isaacvega5" 
    token:
      secure: "b5Ky5+1WunyUNKi4+HfFm+fxR2fqfJoPVQc27AJZrpfjuiJsHbc6PYrc7/JZbhpdQgtXbzF9iitQSBiMnHfS+AzpW/VjuaYKAwldVmrOUOFpgUv5fdaJzJsSHLcWTjj9junAIyF/dUbOXk5vuS22wFPPb6PzWLknsBaVR/FGkG5toKVgs0KH593LupV0sxRudKpwTyeItJzGntylW2zs/9fWqSXDAl9TYTWitzHcPQKjh3Q0BLo7AkY7ZuQQM6LSnuRCyu02CaB38AIIt0YC9TMxkWrKHWSLZ//WuUi0vs07OFx9Fqa/DbmzYdrDaIg4Sw7Xz55ERWyjfywcQmpfK3p8+nS9BrqDnQ06hMA/wdTRqpQPRcrCllhTvGfjFXsyOxjGh11fLoYsrokIG2wOlqU3BnvIb/V8Wug+579yQKSfrYaXr9ZFnMo2C+ClBuXPYT1XVmRoVphlnSD1JvOewe2jfscL5hWDU0hHQUdaAblc1S1C3QY4I+iZm7h78nRNo73qqpKrqlwQTYsMMNhcq1FxyICEoHFA8nlY7AYYsffoZJPObZn9bEt3SF9hqjSXx7SMwB0FpLvO5/G1hEhVe0aULNVXkfH6aE4E0E5/2jNurvojtNwCB4dgq6DrzMdPs5Izq3wM1889QxLQXPDj0IsJQi/9vPx5CSrTSREbdxo="

script:
  - python -m unittest discover -s tests
  - sonar-scanner