language: python
python:
  - "3.9.10"

addons:
  sonarcloud:
    organization: "isaacvega5" 
    token:
      secure: "d63ecd20ff070dfe73624df6da2978baae54dec5" 

script:
  - python -m unittest discover -s tests

  - sonar:sonar - Dsonar.organization=isaacvega5 - Dsonar.projectKey=IsaacVega5_Sonar-prueba - Dsonar.sources=. - Dsonar.host.url=https://sonarcloud.io

