language: python
python:
  - "3.9.10"

addons:
  sonarcloud:
    organization: "isaacvega5" 
    token:
      secure: "f3e9c2e8babf433444ac880f427c45a1f9914927" 

script:
  - python -m unittest discover -s tests
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=myorg_myrepo